-- Migration: Add Manuscript Structure Tables
-- Created: 2025-01-17
-- Purpose: Integrate factory-core manuscript structure (Acts, Chapters, Scenes, Reference Files)

-- Table: manuscript_acts
-- Represents acts in a manuscript (e.g., Act 1, Act 2, Act 3)
CREATE TABLE IF NOT EXISTS manuscript_acts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    volume INTEGER NOT NULL DEFAULT 1,
    act_number INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    notes TEXT DEFAULT '',
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT unique_act_per_project UNIQUE (project_id, volume, act_number)
);

CREATE INDEX idx_manuscript_acts_project_id ON manuscript_acts(project_id);
CREATE INDEX idx_manuscript_acts_volume ON manuscript_acts(project_id, volume);

-- Table: manuscript_chapters
-- Represents chapters within acts
CREATE TABLE IF NOT EXISTS manuscript_chapters (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    act_id UUID NOT NULL REFERENCES manuscript_acts(id) ON DELETE CASCADE,
    chapter_number INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    notes TEXT DEFAULT '',
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT unique_chapter_per_act UNIQUE (act_id, chapter_number)
);

CREATE INDEX idx_manuscript_chapters_act_id ON manuscript_chapters(act_id);

-- Table: manuscript_scenes
-- Represents individual scenes within chapters (the actual prose content)
CREATE TABLE IF NOT EXISTS manuscript_scenes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    chapter_id UUID NOT NULL REFERENCES manuscript_chapters(id) ON DELETE CASCADE,
    scene_number INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT DEFAULT '',  -- The actual prose
    word_count INTEGER DEFAULT 0,
    notes TEXT DEFAULT '',
    metadata JSONB DEFAULT '{}',  -- Generation context, prompts, models used, etc.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT unique_scene_per_chapter UNIQUE (chapter_id, scene_number)
);

CREATE INDEX idx_manuscript_scenes_chapter_id ON manuscript_scenes(chapter_id);
CREATE INDEX idx_manuscript_scenes_word_count ON manuscript_scenes(word_count);

-- Table: reference_files
-- Knowledge base files (characters, world building, plot, themes, etc.)
CREATE TABLE IF NOT EXISTS reference_files (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    category VARCHAR(50) NOT NULL,  -- 'characters', 'world_building', 'story_structure', 'themes', etc.
    subcategory VARCHAR(50) DEFAULT '',  -- 'protagonists', 'locations', 'outline', etc.
    filename VARCHAR(255) NOT NULL,
    content TEXT DEFAULT '',  -- Markdown content
    word_count INTEGER DEFAULT 0,
    metadata JSONB DEFAULT '{}',  -- Tags, source (NotebookLM URL, etc.), version info
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT unique_reference_file UNIQUE (project_id, category, subcategory, filename)
);

CREATE INDEX idx_reference_files_project_id ON reference_files(project_id);
CREATE INDEX idx_reference_files_category ON reference_files(project_id, category);
CREATE INDEX idx_reference_files_search ON reference_files USING GIN (to_tsvector('english', content));

-- Comments
COMMENT ON TABLE manuscript_acts IS 'Acts in a manuscript (e.g., Act 1, Act 2, Act 3). Based on factory-core structure.';
COMMENT ON TABLE manuscript_chapters IS 'Chapters within acts. Allows for structured multi-act novels.';
COMMENT ON TABLE manuscript_scenes IS 'Individual scenes containing the actual prose. Generated by AI with knowledge context.';
COMMENT ON TABLE reference_files IS 'Knowledge base markdown files. Queried by AI for scene generation context.';

COMMENT ON COLUMN manuscript_scenes.metadata IS 'Stores generation context: outline, KB queries used, prompt, model, etc.';
COMMENT ON COLUMN reference_files.metadata IS 'Stores source info: NotebookLM URL, tags, version, etc.';

-- Grant permissions (adjust based on your database user)
-- GRANT ALL PRIVILEGES ON manuscript_acts TO your_db_user;
-- GRANT ALL PRIVILEGES ON manuscript_chapters TO your_db_user;
-- GRANT ALL PRIVILEGES ON manuscript_scenes TO your_db_user;
-- GRANT ALL PRIVILEGES ON reference_files TO your_db_user;
