import { CheckBadgeIcon, SparklesIcon, UserIcon, UsersIcon } from '@heroicons/react/24/solid';
import type { Badge as BadgeType } from '../types';

interface BadgeProps {
  badge: BadgeType;
  size?: 'sm' | 'md' | 'lg';
}

export default function Badge({ badge, size = 'md' }: BadgeProps) {
  const sizeClasses = {
    sm: 'text-xs px-2 py-0.5',
    md: 'text-sm px-3 py-1',
    lg: 'text-base px-4 py-2',
  };

  const iconSizes = {
    sm: 'h-3 w-3',
    md: 'h-4 w-4',
    lg: 'h-5 w-5',
  };

  switch (badge.badge_type) {
    case 'ai_analyzed':
      return (
        <span className={`inline-flex items-center gap-1.5 rounded-full bg-purple-100 text-purple-800 font-medium ${sizeClasses[size]}`}>
          <SparklesIcon className={iconSizes[size]} />
          AI-Analyzed
          {badge.metadata_json?.score && ` (${badge.metadata_json.score}/70)`}
        </span>
      );

    case 'human_verified':
      return (
        <span className={`inline-flex items-center gap-1.5 rounded-full bg-green-100 text-green-800 font-medium ${sizeClasses[size]}`}>
          <CheckBadgeIcon className={iconSizes[size]} />
          Human-Authored
          {badge.metadata_json?.confidence && ` (${badge.metadata_json.confidence}% verified)`}
        </span>
      );

    case 'human_self':
      return (
        <span className={`inline-flex items-center gap-1.5 rounded-full bg-blue-100 text-blue-800 font-medium ${sizeClasses[size]}`}>
          <UserIcon className={iconSizes[size]} />
          Human-Authored (Self-Certified)
        </span>
      );

    case 'community_upload':
      return (
        <span className={`inline-flex items-center gap-1.5 rounded-full bg-gray-100 text-gray-800 font-medium ${sizeClasses[size]}`}>
          <UsersIcon className={iconSizes[size]} />
          Community Upload
        </span>
      );

    default:
      return null;
  }
}

// Badge explainer component for landing page
export function BadgeExplainer() {
  const badges: Array<{ type: BadgeType['badge_type']; title: string; description: string }> = [
    {
      type: 'ai_analyzed',
      title: 'AI-Analyzed',
      description: 'This work was developed using professional AI analysis from Writers Factory, with scores across 7 dimensions of writing craft.',
    },
    {
      type: 'human_verified',
      title: 'Human-Authored (Verified)',
      description: 'Our AI detection system has verified this work was written by a human, not generated by AI. High confidence rating.',
    },
    {
      type: 'human_self',
      title: 'Human-Authored (Self-Certified)',
      description: 'The author has certified this work was written entirely by them without AI assistance.',
    },
    {
      type: 'community_upload',
      title: 'Community Upload',
      description: 'Shared directly by the community without AI analysis or verification.',
    },
  ];

  return (
    <div className="bg-gray-50 py-16">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <h2 className="text-3xl font-bold text-gray-900 mb-8 text-center">
          What Do the Badges Mean?
        </h2>
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {badges.map((badge) => (
            <div key={badge.type} className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
              <div className="mb-4">
                <Badge
                  badge={{
                    id: '',
                    work_id: '',
                    badge_type: badge.type,
                    verified: true,
                    metadata_json: {},
                    created_at: '',
                  }}
                  size="md"
                />
              </div>
              <h3 className="font-semibold text-gray-900 mb-2">{badge.title}</h3>
              <p className="text-sm text-gray-600">{badge.description}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
